# HYPER-PARAMETERS FOR CLASSIFIER

batch_size:     # Number of training examples to consider in each iteration
  - 32

num_epochs:     # Number of times to iterate over tge entire training set
  - 50

kernel_size:    # Kernel size to be used throughout
  - 3           

pool_size:      # Pooling size to be used throughout
  - 2           

conv_depth:
  - 32          # Initial number of kernels in the convolutional layer
  - 64          # Number of kernels in the second convolutional layer

drop_prob:
  - 0.25        # Probability of dropout after pooling
  - 0.5         # Probability of dropout in the fully-connected layer

hidden_size:    # Number of nerons in the fully-connected layer
  - 512