# PARAMETERS FOR MALARIA DIAGNOSIS SYSTEM

cell_detector:
    kernel_size:
    tolerance:
    radius:
    minimum_distance:
    pixels_per_micrometer:
    area_threshold:
classifier:
    augment:
        True
    # Parameters for classifier
    batch_size:     
        # Number of training examples to consider in each iteration
        32
    num_epochs:     
        # Number of times to iterate over tge entire training set
        10
    kernel_size:    
        # Kernel size to be used throughout
        - 3
        - 3
        - 6
        - 6          
    hidden_size:    
        # Number of nerons in the fully-connected layer
        - 512
    pool_size:     
         # Pooling size to be used throughout
        - 2
        - 2     
    conv_depth:
        # Number of filters in the convolutional layer (list)
        - 32            # Number of kernels in the first convolutional layer
        - 32            # Number of kernels in the second convolutional layer
        - 64            # Number of kernels in the third convolutional layer
        - 64            # Number of kernels in the fourth convolutional layer
    drop_prob:
        # Probability of a node droping out when training
        - 0.25        # Probability of dropout after pooling
        - 0.25
        - 0.5         # Probability of dropout in the fully-connected layer
manual_classifier:
    image_height:
    image_width:
    labels: 
    train:
        files:
        destination:
    test: 
        files:
        destination: 
train:
    labels:
        # Labels must be ints starting from 0 (for one-hot encoding)
        0:
            directories:
                # Paths to directories of images
                - "train/mnist/0"
        1:
            directories:
                # Paths to directories of images
                - "train/mnist/1"
        2:
            directories:
                # Paths to directories of images
                - "train/mnist/2"
        3:
            directories:
                # Paths to directories of images
                - "train/mnist/3"
        4:
            directories:
                # Paths to directories of images
                - "train/mnist/4"
        5:
            directories:
                # Paths to directories of images
                - "train/mnist/5"
        6:
            directories:
                # Paths to directories of images
                - "train/mnist/6"
        7:
            directories:
                # Paths to directories of images
                - "train/mnist/7"
        8:
            directories:
                # Paths to directories of images
                - "train/mnist/8"
        9:
            directories:
                # Paths to directories of images
                - "train/mnist/9"
    small_images:
    image_height:
        28
    image_width:
        28
    image_depth:
        3
    resize:
evaluate:
    # Labels must be ints starting from 0 (for one-hot encoding)
    labels:
        0:
            directories:
                # Paths to directories of images
                - "test/mnist/0"
        1:
            directories:
                # Paths to directories of images
                - "test/mnist/1"
        2:
            directories:
                # Paths to directories of images
                - "test/mnist/2"
        3:
            directories:
                # Paths to directories of images
                - "test/mnist/3"
        4:
            directories:
                # Paths to directories of images
                - "test/mnist/4"
        5:
            directories:
                # Paths to directories of images
                - "test/mnist/5"
        6:
            directories:
                # Paths to directories of images
                - "test/mnist/6"
        7:
            directories:
                # Paths to directories of images
                - "test/mnist/7"
        8:
            directories:
                # Paths to directories of images
                - "test/mnist/8"
        9:
            directories:
                # Paths to directories of images
                - "test/mnist/9"
    resize:
    small_images:
    image_height:
        28
    image_width:
        28
    image_depth:
        3
diagnose:
    directories: 
