# PARAMETERS FOR MALARIA DIAGNOSIS SYSTEM

cell_detector:
    # Parameters for cell detector
    kernel_size:
        # Kernel size for applying Gaussian blur (int)
        5
    tolerance:
        # Tolerance in micrometers of red blood cell radius (float)
        0.5
    radius:
        # Radius of a red blood cell in micrometers (float)
        3.5
    minimum_distance:
        # Minimum permissible distance between red blood cell centres (int)
        # Will be set automatically if zero. 
        0
    pixels_per_micrometer:
        # The number of pixels for each micrometer of image (int)
        10
    area_threshold:
        # Percentage of the circle that should contant a cell (float)
        65
neural_network:
    # Parameters for the neural network
    batch_size:     
        # Number of training examples to consider in each iteration (int)
        32
    epochs:     
        # Number of times to iterate over tge entire training set (int)
        150
    kernel_size:    
        # Kernel size to be used throughout (list of ints)
        - 8
        - 8
        - 10
        - 10         
    hidden_size:    
        # Number of nerons in the fully-connected layer (list of ints)
        - 1280
    pool_size:     
         # Pooling size to be used throughout (list of ints)
        - 3
        - 3     
    conv_depth:
        # Number of filters in the convolutional layer (list of ints)
        - 32         
        - 32            
        - 64            
        - 64            
    drop_prob:
        # Probability of a node droping out when training (list of ints)
        - 0.25        
        - 0.25
        - 0.5  
    learn_rate:
        # Learning rate (float)
        0.00001
    augment:
        # To augment data or not (bool)
        False
    activation:
        # Activation function to use (string)
        "elu"
manual_classifier:
    # Parameters for the manual calssifier
    image_height:
        # Height to which cells will be cropped (int)
        80
    image_width:
        # Width to which cells will be cropped (int)
        80
    labels: 
        # Labels that can be assigned to images (list of strings)
        - falciparum
        - healthy
        - not
    train:
        files:
            # Paths to individual images for classification (list of strings)
            # - "train/samples/57546/57546_01.jpg"
            # - "train/samples/57546/57546_02.jpg"
            # - "train/samples/57546/57546_03.jpg"
            # - "train/samples/57546/57546_04.jpg"
            # - "train/samples/57546/57546_05.jpg"
            # - "train/samples/57546/57546_06.jpg"
            # - "train/samples/57546/57546_07.jpg"
            # - "train/samples/57546/57546_08.jpg"
            # - "train/samples/57546/57546_09.jpg"
            # - "train/samples/57546/57546_10.jpg"
            # - "train/samples/57546/57546_11.jpg"
            # - "train/samples/57546/57546_12.jpg"
            # - "train/samples/57546/57546_13.jpg"
            # - "train/samples/57546/57546_14.jpg"
        destination:
            # Destination path for classified images (string)
            "train/cells" 
    test: 
        files:
            # Paths to be classified for evaluation (list of strings)
            # - "test/samples/57546/57546_24.jpg"
            # - "test/samples/57546/57546_23.jpg"
        destination: 
            # Destination paths for classified images (string)
            "test/cells"
images:
    # Image sizes
    height:
        # Height of training images (int)
        80
    width:
        # Width of training images (int)
        80
    depth:
        # Depth of training images (int)
        3
    resize:
        # Size to which images should be resized (int) (optional)
        32
train:
    # Labels and images for training the CNN
    labels:
        0:
            directories:
                # Paths to directories of images (list of strings)
                - "train/cells/healthy/57546"
        1:
            directories:
                # Paths to directories of images (list of strings)
                - "train/cells/falciparum/57546_01"
                - "train/cells/falciparum/57546_02"
                - "train/cells/falciparum/57546_03"
                - "train/cells/falciparum/57546_04"
                - "train/cells/falciparum/57546_05"
                - "train/cells/falciparum/57546_06"
                - "train/cells/falciparum/57546_07"
                - "train/cells/falciparum/57546_08"
                - "train/cells/falciparum/57546_09"
                - "train/cells/falciparum/57546_10"
                - "train/cells/falciparum/57546_11"
                - "train/cells/falciparum/57546_12"
                - "train/cells/falciparum/57546_13"
                - "train/cells/falciparum/57546_14"
    small_images:
        # What to do with images that are smaller that the dimensions given (string) (optional)
        # "pad"
        "ignore"
evaluate:
    # Labels must be ints starting from 0 (for one-hot encoding)
    labels:
        0:
            directories:
                # Paths to directories of images (list)
                - "test/cells/healthy/57546"
        1:
            directories:
                # Paths to directories of images (list)
                - "test/cells/falciparum/57546_24"
    small_images:
        # What to do with images that are smaller that the dimensions given (string) (optional)
        "ignore"
        # "pad"
diagnose:
    # Paths to directory of images that require diagnosis (list of strings)
    directories: 
        - "test/samples/57546"
    destination: 
    # Paths to directory to which results will be saved (string)
        "results/57546"
    small_images:
        # What to do with images that are smaller that the dimensions given (string) (optional)
       "ignore" 



