# PARAMETERS FOR MALARIA DIAGNOSIS SYSTEM

cell_detector:
    kernel_size:
    tolerance:
    radius:
    minimum_distance:
    pixels_per_micrometer:
    area_threshold:
classifier:
    # Parameters for classifier
    batch_size:     
        # Number of training examples to consider in each iteration
        32
    num_epochs:     
        # Number of times to iterate over tge entire training set
        50
    kernel_size:    
        # Kernel size to be used throughout
        3           
    hidden_size:    
        # Number of nerons in the fully-connected layer
        512
    pool_size:     
         # Pooling size to be used throughout
        2    
    conv_depth:
        # Number of filters in the convolutional layer (list)
        - 32          # Initial number of kernels in the convolutional layer
        - 64          # Number of kernels in the second convolutional layer
    drop_prob:
        # Probability of a node droping out when training
        - 0.25        # Probability of dropout after pooling
        - 0.5         # Probability of dropout in the fully-connected layer
manual_classifier:
    image_height:
    image_width:
    labels: 
    train:
        files:
        destination:
    test: 
        files:
        destination: 
train:
    labels:
        # Labels must be ints starting from 0 (for one-hot encoding)
        0:
            directories:
                # Paths to directories of images
                - "train/cifar10/0"
        1:
            directories:
                # Paths to directories of images
                - "train/cifar10/1"
        2:
            directories:
                # Paths to directories of images
                - "train/cifar10/2"
        3:
            directories:
                # Paths to directories of images
                - "train/cifar10/3"
        4:
            directories:
                # Paths to directories of images
                - "train/cifar10/4"
        5:
            directories:
                # Paths to directories of images
                - "train/cifar10/5"
        6:
            directories:
                # Paths to directories of images
                - "train/cifar10/6"
        7:
            directories:
                # Paths to directories of images
                - "train/cifar10/7"
        8:
            directories:
                # Paths to directories of images
                - "train/cifar10/8"
        9:
            directories:
                # Paths to directories of images
                - "train/cifar10/9"
    small_images:
    image_height:
        32
    image_width:
        32
    image_depth:
        3
evaluate:
    # Labels must be ints starting from 0 (for one-hot encoding)
    labels:
        0:
            directories:
                # Paths to directories of images
                - "test/cifar10/0"
        1:
            directories:
                # Paths to directories of images
                - "test/cifar10/1"
        2:
            directories:
                # Paths to directories of images
                - "test/cifar10/2"
        3:
            directories:
                # Paths to directories of images
                - "test/cifar10/3"
        4:
            directories:
                # Paths to directories of images
                - "test/cifar10/4"
        5:
            directories:
                # Paths to directories of images
                - "test/cifar10/5"
        6:
            directories:
                # Paths to directories of images
                - "test/cifar10/6"
        7:
            directories:
                # Paths to directories of images
                - "test/cifar10/7"
        8:
            directories:
                # Paths to directories of images
                - "test/cifar10/8"
        9:
            directories:
                # Paths to directories of images
                - "test/cifar10/9"
    small_images:
    image_height:
        32
    image_width:
        32
    image_depth:
        3
diagnose:
    directories: 
