# PARAMETERS FOR MALARIA DIAGNOSIS SYSTEM

cell_detector:
    # Parameters for cell detector
    kernel_size:
        # Kernel size for applying Gaussian blur (int)
        5

    tolerance:
        # Tolerance in micrometers of red blood cell radius (float)
        0.5

    radius:
        # Radius of a red blood cell in micrometers (float)
        3.5

    minimum_distance:
        # Minimum permissible distance between red blood cell centres (int)
        # Will be set automatically if zero. 
        0

    pixels_per_micrometer:
        # The number of pixels for each micrometer of image (int)
        10

    area_threshold:
        # Percentage of the circle that should contain cell (float)
        65

    labels:
        0:
            - "cells/not_rot"
            - "cells/not_aug"

        1:
            - "cells/healthy/57549/57549_01"
            - "cells/healthy/57513/57513_01"
            - "cells/healthy/57539/57539_01"
            - "cells/healthy/57545/57545_01"
            - "cells/healthy/57546/57546_01"

neural_network:
    # Parameters for the neural network
    batch_size:     
        # Number of training examples to consider in each iteration (int)
        64

    n_batches:
        # Number of batches to split entire training set into (int)
        # Each batched is used for training once, then batches are randomised
        10

    epochs:     
        # Number of times to iterate over tge entire training set (int)
        100

    init:
        "he_normal"

    kernel_size:    
        # Kernel size to be used throughout (list of ints)
        - 4
        - 4
        - 5
        - 5
        - 5
        - 5

    hidden_size:    
        # Number of nerons in the fully-connected layer (list of ints)
        - 1024
        - 1024
        - 1024

    pool_size:
         # Pooling size to be used throughout (list of ints)
        - 2
        - 2
        - 2

    conv_depth:
        # Number of filters in the convolutional layer (list of ints)
        - 32
        - 32
        - 64
        - 64
        - 128
        - 128

    drop_prob:
        # Probability of a node dropping out when training (list of ints)
        - 0.25        
        - 0.25
        - 0.25
        - 0.5
        - 0.5
        - 0.5

    learn_rate:
        # Learning rate (float)
        0.000001

    augment:
        # To augment data or not (bool)
        False # Not implemented yet

    activation:
        # Activation function to use (string)
        "relu"

images:
    # Image sizes
    height:
        # Height of training images (int)
        80

    width:
        # Width of training images (int)
        80

    depth:
        # Depth of training images (int)
        3

train:
    0:
        - "cells/healthy_bal/57502"

    1:
        - "cells/falciparum_bal/57502"

evaluate:
    # Labels must be ints starting from 0 (for one-hot encoding)
    0:
        - "cells/healthy/57517"

    1:
        - "cells/falciparum/57517"


diagnose:
    # Paths to directory of images that require diagnosis (list of strings)
    directories:
        - ""

    destination: 
    # Paths to directory to which results will be saved (string)
        "cells"
