# PARAMETERS FOR MALARIA DIAGNOSIS SYSTEM

cell_detector:
    # Parameters for cell detector
    kernel_size:
        # Kernel size for applying Gaussian blur (int)
        5

    tolerance:
        # Tolerance in micrometers of red blood cell radius (float)
        0.5

    radius:
        # Radius of a red blood cell in micrometers (float)
        3.5

    minimum_distance:
        # Minimum permissible distance between red blood cell centres (int)
        # Will be set automatically if zero. 
        0

    pixels_per_micrometer:
        # The number of pixels for each micrometer of image (int)
        10

    area_threshold:
        # Percentage of the circle that should contant a cell (float)
        65

neural_network:
    # Parameters for the neural network
    batch_size:     
        # Number of training examples to consider in each iteration (int)
        32

    epochs:     
        # Number of times to iterate over tge entire training set (int)
        3

    kernel_size:    
        # Kernel size to be used throughout (list of ints)
        - 4
        - 4
        - 5
        - 5
        - 6
        - 6

    hidden_size:    
        # Number of nerons in the fully-connected layer (list of ints)
        - 1024

    pool_size:     
         # Pooling size to be used throughout (list of ints)
        - 2
        - 2
        - 2

    conv_depth:
        # Number of filters in the convolutional layer (list of ints)
        - 32
        - 32
        - 32
        - 32
        - 64
        - 64

    drop_prob:
        # Probability of a node droping out when training (list of ints)
        - 0.25        
        - 0.25
        - 0.25
        - 0.5 

    learn_rate:
        # Learning rate (float)
        0.00001

    augment:
        # To augment data or not (bool)
        False # Not implemented yet

    activation:
        # Activation function to use (string)
        "relu"

images:
    # Image sizes
    height:
        # Height of training images (int)
        80

    width:
        # Width of training images (int)
        80

    depth:
        # Depth of training images (int)
        3

train:
    # Labels and images for training the CNN
    labels:
        0:
            directories:
                # Paths to directories of images (list of strings)
                - "cells/train/healthy/57546/57546_01"

        1:
            directories:
                # Paths to directories of images (list of strings)
                - "cells/train/falciparum/57546/57546_01"
                - "cells/train/falciparum/57546/57546_02"
                - "cells/train/falciparum/57546/57546_03"
                - "cells/train/falciparum/57546/57546_04"
                - "cells/train/falciparum/57546/57546_05"
                - "cells/train/falciparum/57546/57546_06"
                - "cells/train/falciparum/57546/57546_07"
                - "cells/train/falciparum/57546/57546_08"
                - "cells/train/falciparum/57546/57546_09"
                - "cells/train/falciparum/57546/57546_10"
                - "cells/train/falciparum/57546/57546_11"
                - "cells/train/falciparum/57546/57546_12"
                - "cells/train/falciparum/57546/57546_13"
                - "cells/train/falciparum/57546/57546_14"
                - "cells/train/falciparum/57546/57546_15"
                - "cells/train/falciparum/57546/57546_16"
                - "cells/train/falciparum/57546/57546_17"
                - "cells/train/falciparum/57546/57546_18"
                - "cells/train/falciparum/57546/57546_19"
                - "cells/train/falciparum/57546/57546_20"
                - "cells/train/falciparum/57546/57546_21"
                - "cells/train/falciparum/57546/57546_22"
                - "cells/train/falciparum/57546/57546_23"
                - "cells/train/falciparum/57546/57546_24"

evaluate:
    # Labels must be ints starting from 0 (for one-hot encoding)
    labels:
        0:
            directories:
                # Paths to directories of images (list)
                - "test/cells/healthy/57546_17"
                - "test/cells/healthy/57546_18"
                - "test/cells/healthy/57546_19"
                - "test/cells/healthy/57546_20"
                - "test/cells/healthy/57546_21"
                - "test/cells/healthy/57546_22"
                - "test/cells/healthy/57546_23"
                - "test/cells/healthy/57546_24"

        1:
            directories:
                # Paths to directories of images (list)
                - "test/cells/falciparum/57546_17"
                - "test/cells/falciparum/57546_18"
                - "test/cells/falciparum/57546_19"
                - "test/cells/falciparum/57546_20"
                - "test/cells/falciparum/57546_21"
                - "test/cells/falciparum/57546_22"
                - "test/cells/falciparum/57546_23"
                - "test/cells/falciparum/57546_24"

diagnose:
    # Paths to directory of images that require diagnosis (list of strings)
    directories: 
        - "samples/test/57546"

    destination: 
    # Paths to directory to which results will be saved (string)
        "results"
