# PATHS TO IMAGES OF CELLS FOR CNN EVALUATION FOR EACH CLASS

0:

  images:
    # Paths to individual images

  directories: 
    # Paths to directories of images
    - "test/cells/57546"

1: 

  images:
    # Paths to individual images

  directories: 
    # Paths to directories of images
    - "test/cells/57546"
