# PATHS TO IMAGES OF SAMPLES TO BE MANUALLY CLASSIFIED
# Images can be for training or testing

image_height:
  # Height to crop images to
  90

image_width:
  # Width to crop images to
  90

train: 

  files:
    # Paths to individual images
    - "train/samples/57546/57546_01.jpg"

  directories:
    # Paths to directories of images
    - "train/samples/57546"

  destination:
    - "test/cells"

test: 

  files:
    # Paths to individual images
    - "test/samples/57546/57546_24.jpg"

  directories:
    # Paths to directories of images
    # -"samples/test/57546"

  destination: 
    - "test/cells"

