# PATHS TO SAMPLE IMAGES FOR TESTING

0:
  directories:
    # Paths to directories of images
    - "test/cells/healthy/57546_01"

1:
  directories:
    # Paths to directories of images
    - "test/cells/falciparum/57546_01"

