# PATHS TO SAMPLE IMAGES FOR TESTING

images:
  # Paths to individual images
  # - "test/samples/57546/57546_23.jpg"
  - "test/samples/57546/57546_24.jpg"

directories: 
  # Paths to directories of images
  # - "test/samples/57546"
