# PATHS TO IMAGES OF CELLS FOR TRAINING THE CNN FOR EACH CLASS

0:
  directories:
    # Paths to directories of images
    - "train/cells/healthy/57546_01"

1:
  directories:
    # Paths to directories of images
    - "train/cells/falciparum/57546_01"

