# PATHS TO TRAINING IMAGES

images:
  - "samples/train/train_01_01.jpg"
  - "samples/train/train_01_02.jpg"
  - "samples/train/train_01_03.jpg"
  - "samples/train/train_01_04.jpg"
  - "samples/train/train_01_05.jpg"
  - "samples/train/train_01_06.jpg"
  - "samples/train/train_01_07.jpg"
  - "samples/train/train_01_08.jpg"
  - "samples/train/train_01_09.jpg"
  - "samples/train/train_01_10.jpg"
  - "samples/train/train_01_11.jpg"
  - "samples/train/train_01_12.jpg"
  - "samples/train/train_01_13.jpg"
  - "samples/train/train_01_14.jpg"
  - "samples/train/train_01_15.jpg"